INSERT INTO ROLES (NM_ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (NM_ROLE) VALUES ('ROLE_FREE');
INSERT INTO ROLES (NM_ROLE) VALUES ('ROLE_PREMIUM');

INSERT INTO PESSOAS (CPF, DT_NASC, NM_PESSOA, SOBRENOME, TELEFONE) VALUES ('44083722851',TO_DATE('2005-04-05','YYYY-MM-DD'), 'Matheus Felipe', 'Camarinha Duarte', '11991512776');

INSERT INTO USUARIOS (EMAIL, PASSWORD, PESSOA, USER_ROLE) VALUES ('matheus.duarte.lins@gmail.com','$2a$12$fIN5p6fBM1VPTH.nJn2NMulMwFsNCDkPLsnUlsyYr19IrUOZPqyWq', 1, 1);
-- senha: Matheus@1

INSERT INTO CONFIGURACOES_DE_COLETA (NM_CONFIG, DESCRICAO_CONFIG, TEMPERATURA_MAX, UMIDADE_MIN, TEMPO_DE_UMIDADE_MIN, INTERVALO_DE_HORAS, USUARIO_PERTENCENTE) VALUES ('Temperatura alta (padrão)', 'Nesta configuração padrao, um jato é lançado quando chegar a 60º', 60, 0, 0, 0, 1);
INSERT INTO CONFIGURACOES_DE_COLETA (NM_CONFIG, DESCRICAO_CONFIG, TEMPERATURA_MAX, UMIDADE_MIN, TEMPO_DE_UMIDADE_MIN, INTERVALO_DE_HORAS, USUARIO_PERTENCENTE) VALUES ('Temperatura alta (sensível)', 'Nesta configuração padrao, um jato é lançado quando chegar a 40º', 40, 0, 0, 0, 1);
INSERT INTO CONFIGURACOES_DE_COLETA (NM_CONFIG, DESCRICAO_CONFIG, TEMPERATURA_MAX, UMIDADE_MIN, TEMPO_DE_UMIDADE_MIN, INTERVALO_DE_HORAS, USUARIO_PERTENCENTE) VALUES ('Umidade baixa 4 Horas', 'Nesta configuração padrao, um jato é lançado quando a umidade permanecer baixo por 4 horas', 0, 15, 4, 0, 1);
INSERT INTO CONFIGURACOES_DE_COLETA (NM_CONFIG, DESCRICAO_CONFIG, TEMPERATURA_MAX, UMIDADE_MIN, TEMPO_DE_UMIDADE_MIN, INTERVALO_DE_HORAS, USUARIO_PERTENCENTE) VALUES ('Umidade baixa 12 Horas', 'Nesta configuração padrao, um jato é lançado quando a umidade permanecer baixo por 12 horas', 0, 15, 12, 0, 1);
INSERT INTO CONFIGURACOES_DE_COLETA (NM_CONFIG, DESCRICAO_CONFIG, TEMPERATURA_MAX, UMIDADE_MIN, TEMPO_DE_UMIDADE_MIN, INTERVALO_DE_HORAS, USUARIO_PERTENCENTE) VALUES ('Lançar Jato Diariamente', 'Esta configuracao padrao lança um jato diariamente', 0, 0, 0, 24, 1);

INSERT INTO DISPOSITIVOS (NM_DISPOSITIVO, MARCA, IDENTIFICADOR, DONO, CONFIG_ATUAL) VALUES ('Placa Central', 'Solar Options', '999MM9MM9', 1, 1);
INSERT INTO DISPOSITIVOS (NM_DISPOSITIVO, MARCA, IDENTIFICADOR, DONO, CONFIG_ATUAL) VALUES ('Placa Direita', 'Solar Options', '999MM9MM8', 1, 3);
INSERT INTO DISPOSITIVOS (NM_DISPOSITIVO, MARCA, IDENTIFICADOR, DONO, CONFIG_ATUAL) VALUES ('Placa Esquerda', 'Solar Options', '999MM9MM7', 1, 5);
